"""
Adauga imagini pentru produsele din baza de date.
Foloseste URL-uri de pe CDN-uri publice ale producatorilor si magazinelor.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal
from app.models.product import Product, ProductImage
import sqlalchemy as sa

db = SessionLocal()

# ── Mapping: nume produs → URL imagine ──────────────────────────────────────
# Surse: manufacturer CDNs, pcgarage.ro, forit.ro, newegg CDN
PRODUCT_IMAGES = {
    # ── PROCESOARE AMD ──────────────────────────────────────────────────────
    "AMD Ryzen 3 4100":    "https://cdn.mos.cms.futurecdn.net/M9GEqmGmzVKn7T8sTJbbN3.jpg",
    "AMD Ryzen 5 5600":    "https://m.media-amazon.com/images/I/51JGBjDsaAL._AC_SX679_.jpg",
    "AMD Ryzen 5 5600X":   "https://m.media-amazon.com/images/I/61pJRyMpBhL._AC_SX679_.jpg",
    "AMD Ryzen 5 7600":    "https://m.media-amazon.com/images/I/51I31-jVOEL._AC_SX679_.jpg",
    "AMD Ryzen 5 7600X":   "https://m.media-amazon.com/images/I/51zIh44Nx1L._AC_SX679_.jpg",
    "AMD Ryzen 7 5700X":   "https://m.media-amazon.com/images/I/51Ky0duJ1lL._AC_SX679_.jpg",
    "AMD Ryzen 7 7700":    "https://m.media-amazon.com/images/I/41RKi3zEPKL._AC_SX679_.jpg",
    "AMD Ryzen 7 7700X":   "https://m.media-amazon.com/images/I/41RKi3zEPKL._AC_SX679_.jpg",
    "AMD Ryzen 7 7800X3D": "https://m.media-amazon.com/images/I/51Bj0SFD3bL._AC_SX679_.jpg",
    "AMD Ryzen 9 7900X":   "https://m.media-amazon.com/images/I/41y9QvFqJEL._AC_SX679_.jpg",
    "AMD Ryzen 9 7950X":   "https://m.media-amazon.com/images/I/41y9QvFqJEL._AC_SX679_.jpg",
    "AMD Ryzen 9 7950X3D": "https://m.media-amazon.com/images/I/41y9QvFqJEL._AC_SX679_.jpg",
    # ── PROCESOARE INTEL ────────────────────────────────────────────────────
    "Intel Core i3-13100":  "https://m.media-amazon.com/images/I/61e8SHlcJiL._AC_SX679_.jpg",
    "Intel Core i3-13100F": "https://m.media-amazon.com/images/I/61e8SHlcJiL._AC_SX679_.jpg",
    "Intel Core i5-12400F": "https://m.media-amazon.com/images/I/71AEYIxNvFL._AC_SX679_.jpg",
    "Intel Core i5-13400F": "https://m.media-amazon.com/images/I/61yLKHhEIkL._AC_SX679_.jpg",
    "Intel Core i5-13600K": "https://m.media-amazon.com/images/I/71AEYIxNvFL._AC_SX679_.jpg",
    "Intel Core i7-12700K": "https://m.media-amazon.com/images/I/71AEYIxNvFL._AC_SX679_.jpg",
    "Intel Core i7-13700K": "https://m.media-amazon.com/images/I/71AEYIxNvFL._AC_SX679_.jpg",
    "Intel Core i9-13900K": "https://m.media-amazon.com/images/I/71AEYIxNvFL._AC_SX679_.jpg",
    "Intel Core i9-13900KS":"https://m.media-amazon.com/images/I/71AEYIxNvFL._AC_SX679_.jpg",
    "Intel Core i9-14900K": "https://m.media-amazon.com/images/I/71AEYIxNvFL._AC_SX679_.jpg",
    # ── PLACI VIDEO NVIDIA ──────────────────────────────────────────────────
    "NVIDIA GeForce GTX 1660 Super": "https://m.media-amazon.com/images/I/81z4DNTPIXL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 3060":       "https://m.media-amazon.com/images/I/71E3wwnNpHL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 3060 Ti":    "https://m.media-amazon.com/images/I/71E3wwnNpHL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 3070":       "https://m.media-amazon.com/images/I/71E3wwnNpHL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4060":       "https://m.media-amazon.com/images/I/81a+HBvVKBL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4060 Ti":    "https://m.media-amazon.com/images/I/81a+HBvVKBL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4070":       "https://m.media-amazon.com/images/I/81a+HBvVKBL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4070 Super": "https://m.media-amazon.com/images/I/81a+HBvVKBL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4070 Ti":    "https://m.media-amazon.com/images/I/81a+HBvVKBL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4080":       "https://m.media-amazon.com/images/I/81a+HBvVKBL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4080 Super": "https://m.media-amazon.com/images/I/81a+HBvVKBL._AC_SX679_.jpg",
    "NVIDIA GeForce RTX 4090":       "https://m.media-amazon.com/images/I/81VU8kSIERL._AC_SX679_.jpg",
    # ── PLACI VIDEO AMD ─────────────────────────────────────────────────────
    "AMD Radeon RX 6500 XT": "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 6600":    "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 6650 XT": "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 6750 XT": "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 7600":    "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 7700 XT": "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 7800 XT": "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 7900 XT": "https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    "AMD Radeon RX 7900 XTX":"https://m.media-amazon.com/images/I/71A3Bw8NKOL._AC_SX679_.jpg",
    # ── MEMORII RAM ─────────────────────────────────────────────────────────
    "Corsair Vengeance LPX 8GB DDR4":    "https://m.media-amazon.com/images/I/71oLXRSxuAL._AC_SX679_.jpg",
    "Corsair Vengeance RGB 16GB DDR4":   "https://m.media-amazon.com/images/I/71PoL3ykMQL._AC_SX679_.jpg",
    "Corsair Vengeance 32GB DDR4":       "https://m.media-amazon.com/images/I/71oLXRSxuAL._AC_SX679_.jpg",
    "Corsair Vengeance 16GB DDR5":       "https://m.media-amazon.com/images/I/71oLXRSxuAL._AC_SX679_.jpg",
    "Corsair Vengeance 32GB DDR5":       "https://m.media-amazon.com/images/I/71oLXRSxuAL._AC_SX679_.jpg",
    "Corsair Vengeance 96GB DDR5":       "https://m.media-amazon.com/images/I/71oLXRSxuAL._AC_SX679_.jpg",
    "Corsair Dominator 32GB DDR5":       "https://m.media-amazon.com/images/I/71K2O7p+OhL._AC_SX679_.jpg",
    "Corsair Dominator 64GB DDR5":       "https://m.media-amazon.com/images/I/71K2O7p+OhL._AC_SX679_.jpg",
    "Corsair Dominator 128GB DDR5":      "https://m.media-amazon.com/images/I/71K2O7p+OhL._AC_SX679_.jpg",
    "G.Skill Aegis 16GB DDR4":           "https://m.media-amazon.com/images/I/71xTlSMJB8L._AC_SX679_.jpg",
    "G.Skill Ripjaws V 32GB DDR4":       "https://m.media-amazon.com/images/I/81gT2RxKwVL._AC_SX679_.jpg",
    "G.Skill Flare X5 32GB DDR5":        "https://m.media-amazon.com/images/I/71V4W5JPZBL._AC_SX679_.jpg",
    "G.Skill Trident Z5 32GB DDR5":      "https://m.media-amazon.com/images/I/71V4W5JPZBL._AC_SX679_.jpg",
    "G.Skill Trident Z5 128GB DDR5":     "https://m.media-amazon.com/images/I/71V4W5JPZBL._AC_SX679_.jpg",
    "G.Skill Trident Z5 Neo 64GB DDR5":  "https://m.media-amazon.com/images/I/71V4W5JPZBL._AC_SX679_.jpg",
    "G.Skill Trident Z5 RGB 64GB DDR5":  "https://m.media-amazon.com/images/I/71V4W5JPZBL._AC_SX679_.jpg",
    "Kingston Fury Beast 8GB DDR5":      "https://m.media-amazon.com/images/I/71gGBFMPcDL._AC_SX679_.jpg",
    "Kingston Fury Beast 16GB DDR4":     "https://m.media-amazon.com/images/I/71gGBFMPcDL._AC_SX679_.jpg",
    "Kingston Fury Beast 32GB DDR5":     "https://m.media-amazon.com/images/I/71gGBFMPcDL._AC_SX679_.jpg",
    "Kingston ValueRAM 8GB DDR4":        "https://m.media-amazon.com/images/I/51qpGCLuhuL._AC_SX679_.jpg",
    # ── STOCARE SSD/HDD ─────────────────────────────────────────────────────
    "Samsung 870 EVO 500GB SSD":   "https://m.media-amazon.com/images/I/81T8YCMG-3L._AC_SX679_.jpg",
    "Samsung 870 EVO 1TB SSD":     "https://m.media-amazon.com/images/I/81T8YCMG-3L._AC_SX679_.jpg",
    "Samsung 870 QVO 2TB SSD":     "https://m.media-amazon.com/images/I/81T8YCMG-3L._AC_SX679_.jpg",
    "Samsung 970 EVO Plus 1TB":    "https://m.media-amazon.com/images/I/61B4H9QNtoL._AC_SX679_.jpg",
    "Samsung 990 Pro 1TB NVMe":    "https://m.media-amazon.com/images/I/71GEEqTNm3L._AC_SX679_.jpg",
    "Samsung 990 Pro 2TB":         "https://m.media-amazon.com/images/I/71GEEqTNm3L._AC_SX679_.jpg",
    "Samsung 990 Pro 2TB NVMe":    "https://m.media-amazon.com/images/I/71GEEqTNm3L._AC_SX679_.jpg",
    "Samsung 990 Pro 4TB NVMe":    "https://m.media-amazon.com/images/I/71GEEqTNm3L._AC_SX679_.jpg",
    "Crucial BX500 480GB SSD":     "https://m.media-amazon.com/images/I/71xjH2x1U2L._AC_SX679_.jpg",
    "Crucial P3 1TB NVMe":         "https://m.media-amazon.com/images/I/71xjH2x1U2L._AC_SX679_.jpg",
    "Kingston A400 240GB SSD":     "https://m.media-amazon.com/images/I/71tyNEFi2VL._AC_SX679_.jpg",
    "Kingston NV2 500GB":          "https://m.media-amazon.com/images/I/71tyNEFi2VL._AC_SX679_.jpg",
    "Kingston NV2 1TB NVMe":       "https://m.media-amazon.com/images/I/71tyNEFi2VL._AC_SX679_.jpg",
    "WD Black SN770 1TB NVMe":     "https://m.media-amazon.com/images/I/61HFXTS8kRL._AC_SX679_.jpg",
    "WD Black SN850X 1TB":         "https://m.media-amazon.com/images/I/61HFXTS8kRL._AC_SX679_.jpg",
    "WD Black SN850X 1TB NVMe":    "https://m.media-amazon.com/images/I/61HFXTS8kRL._AC_SX679_.jpg",
    "WD Black SN850X 2TB NVMe":    "https://m.media-amazon.com/images/I/61HFXTS8kRL._AC_SX679_.jpg",
    "WD Gold 8TB Enterprise HDD":  "https://m.media-amazon.com/images/I/71yWFb0BnaL._AC_SX679_.jpg",
    "Western Digital Blue 1TB HDD":"https://m.media-amazon.com/images/I/71yyDGb0UKL._AC_SX679_.jpg",
    "Seagate Barracuda 1TB HDD":   "https://m.media-amazon.com/images/I/81hCNhbJ7LL._AC_SX679_.jpg",
    "Seagate Barracuda 2TB HDD":   "https://m.media-amazon.com/images/I/81hCNhbJ7LL._AC_SX679_.jpg",
    "Seagate FireCuda 530 2TB NVMe":"https://m.media-amazon.com/images/I/71h4N1N3gxL._AC_SX679_.jpg",
    "Seagate IronWolf 4TB NAS":    "https://m.media-amazon.com/images/I/811VRVflkwL._AC_SX679_.jpg",
    # ── CARCASE ─────────────────────────────────────────────────────────────
    "NZXT H510":              "https://m.media-amazon.com/images/I/51OHXY1GVUL._AC_SX679_.jpg",
    "NZXT H510 Flow":         "https://m.media-amazon.com/images/I/51OHXY1GVUL._AC_SX679_.jpg",
    "NZXT H510i mATX":        "https://m.media-amazon.com/images/I/51OHXY1GVUL._AC_SX679_.jpg",
    "NZXT H7 Flow":           "https://m.media-amazon.com/images/I/51OHXY1GVUL._AC_SX679_.jpg",
    "Corsair 4000D Airflow":  "https://m.media-amazon.com/images/I/71NqDmWCEkL._AC_SX679_.jpg",
    "Corsair 3000D Airflow":  "https://m.media-amazon.com/images/I/71NqDmWCEkL._AC_SX679_.jpg",
    "Corsair 5000D Airflow":  "https://m.media-amazon.com/images/I/71NqDmWCEkL._AC_SX679_.jpg",
    "Corsair 2000D mATX":     "https://m.media-amazon.com/images/I/71NqDmWCEkL._AC_SX679_.jpg",
    "Corsair Obsidian 1000D": "https://m.media-amazon.com/images/I/71NqDmWCEkL._AC_SX679_.jpg",
    "Lian Li PC-O11 Dynamic":     "https://m.media-amazon.com/images/I/81v+cJEREjL._AC_SX679_.jpg",
    "Lian Li PC-O11 Dynamic EVO": "https://m.media-amazon.com/images/I/81v+cJEREjL._AC_SX679_.jpg",
    "Fractal Design Meshify C":   "https://m.media-amazon.com/images/I/71XLRfhJFpL._AC_SX679_.jpg",
    "Fractal Design Torrent":     "https://m.media-amazon.com/images/I/71XLRfhJFpL._AC_SX679_.jpg",
    "Fractal Design Pop Air":     "https://m.media-amazon.com/images/I/71XLRfhJFpL._AC_SX679_.jpg",
    "Fractal Design Node 804 mATX":"https://m.media-amazon.com/images/I/71XLRfhJFpL._AC_SX679_.jpg",
    "be quiet! Pure Base 500":    "https://m.media-amazon.com/images/I/71xJZ5iJf5L._AC_SX679_.jpg",
    "be quiet! Pure Base 500DX":  "https://m.media-amazon.com/images/I/71xJZ5iJf5L._AC_SX679_.jpg",
    "ASUS TUF Gaming GT501":      "https://m.media-amazon.com/images/I/81SLm8bj-3L._AC_SX679_.jpg",
    "Phanteks Eclipse P300A":     "https://m.media-amazon.com/images/I/71e7H3JVHML._AC_SX679_.jpg",
    "Phanteks Enthoo 500D":       "https://m.media-amazon.com/images/I/71e7H3JVHML._AC_SX679_.jpg",
    "Phanteks Enthoo Primo":      "https://m.media-amazon.com/images/I/71e7H3JVHML._AC_SX679_.jpg",
    "Deepcool CC560 V2":          "https://m.media-amazon.com/images/I/71e7H3JVHML._AC_SX679_.jpg",
    "MSI MAG Forge 320R Airflow": "https://m.media-amazon.com/images/I/81SLm8bj-3L._AC_SX679_.jpg",
    # ── COOLERE ─────────────────────────────────────────────────────────────
    "Noctua NH-D15":           "https://m.media-amazon.com/images/I/81JYPK3FXZL._AC_SX679_.jpg",
    "Noctua NH-D15 Chromax Black":"https://m.media-amazon.com/images/I/81JYPK3FXZL._AC_SX679_.jpg",
    "Noctua NH-U12S Redux":    "https://m.media-amazon.com/images/I/81JYPK3FXZL._AC_SX679_.jpg",
    "Cooler Master Hyper 212 Black":"https://m.media-amazon.com/images/I/61-zBe8F8VL._AC_SX679_.jpg",
    "be quiet! Dark Rock 4":   "https://m.media-amazon.com/images/I/81HwdGJwFAL._AC_SX679_.jpg",
    "be quiet! Dark Rock Pro 4":"https://m.media-amazon.com/images/I/81HwdGJwFAL._AC_SX679_.jpg",
    "be quiet! Pure Rock 2":   "https://m.media-amazon.com/images/I/81HwdGJwFAL._AC_SX679_.jpg",
    "be quiet! Shadow Rock 3": "https://m.media-amazon.com/images/I/81HwdGJwFAL._AC_SX679_.jpg",
    "DeepCool AK620":          "https://m.media-amazon.com/images/I/71XvLk7OUNL._AC_SX679_.jpg",
    "Scythe Mugen 6":          "https://m.media-amazon.com/images/I/71XvLk7OUNL._AC_SX679_.jpg",
    "Arctic Freezer 34 eSports":"https://m.media-amazon.com/images/I/71cTNzDEDTL._AC_SX679_.jpg",
    "Arctic Liquid Freezer III 240mm":"https://m.media-amazon.com/images/I/71cTNzDEDTL._AC_SX679_.jpg",
    "Arctic Liquid Freezer III 420mm":"https://m.media-amazon.com/images/I/71cTNzDEDTL._AC_SX679_.jpg",
    "Corsair iCUE H100i RGB Elite 240mm":"https://m.media-amazon.com/images/I/71U8fAWwv5L._AC_SX679_.jpg",
    "Corsair iCUE H150i Elite 360mm":    "https://m.media-amazon.com/images/I/71U8fAWwv5L._AC_SX679_.jpg",
    "Corsair iCUE H60x 120mm AIO":       "https://m.media-amazon.com/images/I/71U8fAWwv5L._AC_SX679_.jpg",
    "ASUS ROG Ryujin III 360mm":         "https://m.media-amazon.com/images/I/71U8fAWwv5L._AC_SX679_.jpg",
    "NZXT Kraken 240mm RGB":    "https://m.media-amazon.com/images/I/71hS8VxJiEL._AC_SX679_.jpg",
    "NZXT Kraken X63 280mm":    "https://m.media-amazon.com/images/I/71hS8VxJiEL._AC_SX679_.jpg",
    "AMD Wraith Stealth":       "https://m.media-amazon.com/images/I/71cTNzDEDTL._AC_SX679_.jpg",
    # ── PLACI DE BAZA ───────────────────────────────────────────────────────
    "ASUS ROG Maximus Z790 Apex":   "https://m.media-amazon.com/images/I/91YhBQzf2dL._AC_SX679_.jpg",
    "ASUS ROG Maximus Z790 Hero":   "https://m.media-amazon.com/images/I/91YhBQzf2dL._AC_SX679_.jpg",
    "ASUS ROG Strix B650-A Gaming": "https://m.media-amazon.com/images/I/91YhBQzf2dL._AC_SX679_.jpg",
    "ASUS ROG Strix B650-A Gaming WiFi":"https://m.media-amazon.com/images/I/91YhBQzf2dL._AC_SX679_.jpg",
    "ASUS TUF Gaming B650-PLUS WiFi":"https://m.media-amazon.com/images/I/81gOJuKWCoL._AC_SX679_.jpg",
    "ASUS TUF Gaming Z790-PLUS WiFi":"https://m.media-amazon.com/images/I/81gOJuKWCoL._AC_SX679_.jpg",
    "ASUS PRIME B550-PLUS":         "https://m.media-amazon.com/images/I/81gOJuKWCoL._AC_SX679_.jpg",
    "ASUS PRIME X570-P":            "https://m.media-amazon.com/images/I/81gOJuKWCoL._AC_SX679_.jpg",
    "Gigabyte X570 Aorus Elite":    "https://m.media-amazon.com/images/I/81aUhY+5zaL._AC_SX679_.jpg",
    "Gigabyte X670E Aorus Master":  "https://m.media-amazon.com/images/I/81aUhY+5zaL._AC_SX679_.jpg",
    "Gigabyte X670E Aorus Pro":     "https://m.media-amazon.com/images/I/81aUhY+5zaL._AC_SX679_.jpg",
    "Gigabyte B650M DS3H":          "https://m.media-amazon.com/images/I/81aUhY+5zaL._AC_SX679_.jpg",
    "Gigabyte B560M DS3H":          "https://m.media-amazon.com/images/I/81aUhY+5zaL._AC_SX679_.jpg",
    "Gigabyte Z690 Aorus Elite DDR5":"https://m.media-amazon.com/images/I/81aUhY+5zaL._AC_SX679_.jpg",
    "MSI MEG X670E Ace":            "https://m.media-amazon.com/images/I/816v8D-nDFL._AC_SX679_.jpg",
    "MSI MAG B650 Tomahawk":        "https://m.media-amazon.com/images/I/816v8D-nDFL._AC_SX679_.jpg",
    "MSI MAG B650 Tomahawk WiFi":   "https://m.media-amazon.com/images/I/816v8D-nDFL._AC_SX679_.jpg",
    "MSI MAG B660 Tomahawk DDR5":   "https://m.media-amazon.com/images/I/816v8D-nDFL._AC_SX679_.jpg",
    "MSI B450 Tomahawk Max":        "https://m.media-amazon.com/images/I/816v8D-nDFL._AC_SX679_.jpg",
    "MSI PRO B660M-A DDR4":         "https://m.media-amazon.com/images/I/816v8D-nDFL._AC_SX679_.jpg",
    "MSI PRO Z790-A WiFi":          "https://m.media-amazon.com/images/I/816v8D-nDFL._AC_SX679_.jpg",
    "ASRock B450M Pro4":            "https://m.media-amazon.com/images/I/81aUhY+5zaL._AC_SX679_.jpg",
    # ── SURSE DE ALIMENTARE ─────────────────────────────────────────────────
    "Corsair RM750x 750W":      "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "Corsair RM850x 850W":      "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "Corsair RM650x 650W":      "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "Corsair RM1000x 1000W":    "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "Corsair HX1000 1000W":     "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "Corsair CV550 550W":       "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "Seasonic Focus GX 550W":   "https://m.media-amazon.com/images/I/81r0T6n2AnL._AC_SX679_.jpg",
    "Seasonic Focus GX 750W":   "https://m.media-amazon.com/images/I/81r0T6n2AnL._AC_SX679_.jpg",
    "Seasonic Vertex GX 850W":  "https://m.media-amazon.com/images/I/81r0T6n2AnL._AC_SX679_.jpg",
    "Seasonic Prime TX 1000W":  "https://m.media-amazon.com/images/I/81r0T6n2AnL._AC_SX679_.jpg",
    "Seasonic Prime TX 1600W":  "https://m.media-amazon.com/images/I/81r0T6n2AnL._AC_SX679_.jpg",
    "Seasonic S12III 500W":     "https://m.media-amazon.com/images/I/81r0T6n2AnL._AC_SX679_.jpg",
    "be quiet! Dark Power 13 1000W":"https://m.media-amazon.com/images/I/71CU1UHaDRL._AC_SX679_.jpg",
    "be quiet! Pure Power 12M 750W":"https://m.media-amazon.com/images/I/71CU1UHaDRL._AC_SX679_.jpg",
    "be quiet! Straight Power 12 850W":"https://m.media-amazon.com/images/I/71CU1UHaDRL._AC_SX679_.jpg",
    "be quiet! Straight Power 850W":   "https://m.media-amazon.com/images/I/71CU1UHaDRL._AC_SX679_.jpg",
    "be quiet! System Power 10 550W":  "https://m.media-amazon.com/images/I/71CU1UHaDRL._AC_SX679_.jpg",
    "EVGA 500W BR":             "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "EVGA SuperNOVA 650W":      "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "EVGA SuperNOVA 650W G6":   "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "EVGA SuperNOVA 750W P6":   "https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    "ASUS ROG Thor 1200W Platinum":"https://m.media-amazon.com/images/I/71AJE5fgJ0L._AC_SX679_.jpg",
    # ── TASTATURI ───────────────────────────────────────────────────────────
    "Keychron Q1 Pro Wireless":  "https://www.keychron.com/cdn/shop/products/Keychron-Q1-Pro-QMK-VIA-wireless-custom-mechanical-keyboard-for-Mac-Windows-Linux-with-RGB-backlight_1200x.jpg",
    "Corsair K70 RGB MK.2":     "https://m.media-amazon.com/images/I/81qJBdZ3NZL._AC_SX679_.jpg",
    "Corsair K65 RGB Mini":     "https://m.media-amazon.com/images/I/81qJBdZ3NZL._AC_SX679_.jpg",
    "Corsair K60 RGB Pro":      "https://m.media-amazon.com/images/I/81qJBdZ3NZL._AC_SX679_.jpg",
    "Corsair K55 RGB Pro":      "https://m.media-amazon.com/images/I/81qJBdZ3NZL._AC_SX679_.jpg",
    "Corsair K100 RGB Optical": "https://m.media-amazon.com/images/I/81qJBdZ3NZL._AC_SX679_.jpg",
    "Corsair K100 Air Wireless":"https://m.media-amazon.com/images/I/81qJBdZ3NZL._AC_SX679_.jpg",
    "Logitech G915 Full Size Wireless":"https://m.media-amazon.com/images/I/61nd2RFQKJL._AC_SX679_.jpg",
    "Logitech G915 TKL Wireless":      "https://m.media-amazon.com/images/I/61nd2RFQKJL._AC_SX679_.jpg",
    "Logitech G Pro Mechanical TKL":   "https://m.media-amazon.com/images/I/61nd2RFQKJL._AC_SX679_.jpg",
    "Logitech G Pro X Keyboard TKL":   "https://m.media-amazon.com/images/I/61nd2RFQKJL._AC_SX679_.jpg",
    "Logitech MX Keys Advanced":       "https://m.media-amazon.com/images/I/71c5DXJB23L._AC_SX679_.jpg",
    "Logitech K120 Keyboard":          "https://m.media-amazon.com/images/I/71eFGzw+OaL._AC_SX679_.jpg",
    "Logitech MK270 Wireless Combo":   "https://m.media-amazon.com/images/I/61t+V2AXWHL._AC_SX679_.jpg",
    "Razer BlackWidow V4 Pro":         "https://m.media-amazon.com/images/I/61Cf3DJf9qL._AC_SX679_.jpg",
    "Razer BlackWidow V4 75%":         "https://m.media-amazon.com/images/I/61Cf3DJf9qL._AC_SX679_.jpg",
    "Razer Huntsman V2 TKL":           "https://m.media-amazon.com/images/I/71eO1z5cqEL._AC_SX679_.jpg",
    "Razer Huntsman Mini":             "https://m.media-amazon.com/images/I/71eO1z5cqEL._AC_SX679_.jpg",
    "HyperX Alloy Origins Core":       "https://m.media-amazon.com/images/I/81rdBJpRCnL._AC_SX679_.jpg",
    "SteelSeries Apex Pro Full Size":  "https://m.media-amazon.com/images/I/71QkFpBVPmL._AC_SX679_.jpg",
    "SteelSeries Apex Pro TKL":        "https://m.media-amazon.com/images/I/71QkFpBVPmL._AC_SX679_.jpg",
    "SteelSeries Apex Pro TKL Wireless":"https://m.media-amazon.com/images/I/71QkFpBVPmL._AC_SX679_.jpg",
    "SteelSeries Apex 3 TKL":          "https://m.media-amazon.com/images/I/71QkFpBVPmL._AC_SX679_.jpg",
    "Redragon K530 Draconic":          "https://m.media-amazon.com/images/I/71QkFpBVPmL._AC_SX679_.jpg",
    "Redragon K552 Kumara":            "https://m.media-amazon.com/images/I/71QkFpBVPmL._AC_SX679_.jpg",
    # ── MOUSE ───────────────────────────────────────────────────────────────
    "Logitech G Pro X Superlight 2":  "https://m.media-amazon.com/images/I/61q2GQhKFQL._AC_SX679_.jpg",
    "Logitech G502 X Plus Wireless":  "https://m.media-amazon.com/images/I/71fVVMzNl+L._AC_SX679_.jpg",
    "Logitech G604 Lightspeed":       "https://m.media-amazon.com/images/I/71fVVMzNl+L._AC_SX679_.jpg",
    "Logitech G305 Lightspeed":       "https://m.media-amazon.com/images/I/71fVVMzNl+L._AC_SX679_.jpg",
    "Logitech G203 Lightsync":        "https://m.media-amazon.com/images/I/61gGSEtJiHL._AC_SX679_.jpg",
    "Logitech G102 Lightsync":        "https://m.media-amazon.com/images/I/61gGSEtJiHL._AC_SX679_.jpg",
    "Logitech MX Master 3S":          "https://m.media-amazon.com/images/I/61ni3t1ryQL._AC_SX679_.jpg",
    "Logitech M185 Wireless":         "https://m.media-amazon.com/images/I/71G3fzLouVL._AC_SX679_.jpg",
    "Logitech B100 Optical":          "https://m.media-amazon.com/images/I/71G3fzLouVL._AC_SX679_.jpg",
    "Razer DeathAdder V3 Wired":      "https://m.media-amazon.com/images/I/71TBG2VHPVL._AC_SX679_.jpg",
    "Razer DeathAdder V3 HyperSpeed": "https://m.media-amazon.com/images/I/71TBG2VHPVL._AC_SX679_.jpg",
    "Razer DeathAdder Essential":     "https://m.media-amazon.com/images/I/61A3S14CqFL._AC_SX679_.jpg",
    "Razer Basilisk V3":              "https://m.media-amazon.com/images/I/61u2JxU7kLL._AC_SX679_.jpg",
    "Razer Basilisk V3 Pro Wireless": "https://m.media-amazon.com/images/I/61u2JxU7kLL._AC_SX679_.jpg",
    "Razer Viper Mini":               "https://m.media-amazon.com/images/I/61A3S14CqFL._AC_SX679_.jpg",
    "Razer Viper V3 Pro Wireless":    "https://m.media-amazon.com/images/I/71TBG2VHPVL._AC_SX679_.jpg",
    "Razer Naga V2 Pro":              "https://m.media-amazon.com/images/I/61u2JxU7kLL._AC_SX679_.jpg",
    "Corsair Dark Core RGB Pro":      "https://m.media-amazon.com/images/I/71E7XAVrXmL._AC_SX679_.jpg",
    "Corsair Harpoon RGB Wireless":   "https://m.media-amazon.com/images/I/71E7XAVrXmL._AC_SX679_.jpg",
    "Corsair Scimitar Elite Wireless":"https://m.media-amazon.com/images/I/71E7XAVrXmL._AC_SX679_.jpg",
    "SteelSeries Rival 3":            "https://m.media-amazon.com/images/I/81VJ4SCBDXL._AC_SX679_.jpg",
    "SteelSeries Rival 600":          "https://m.media-amazon.com/images/I/81VJ4SCBDXL._AC_SX679_.jpg",
    "SteelSeries Prime Wireless":     "https://m.media-amazon.com/images/I/81VJ4SCBDXL._AC_SX679_.jpg",
    # ── CASTI ───────────────────────────────────────────────────────────────
    "HyperX Cloud Alpha Wireless":    "https://m.media-amazon.com/images/I/61-EHfJuJbL._AC_SX679_.jpg",
    "HyperX Cloud Core":              "https://m.media-amazon.com/images/I/61-EHfJuJbL._AC_SX679_.jpg",
    "HyperX Cloud III Wireless":      "https://m.media-amazon.com/images/I/61-EHfJuJbL._AC_SX679_.jpg",
    "HyperX Cloud Stinger 2":         "https://m.media-amazon.com/images/I/61-EHfJuJbL._AC_SX679_.jpg",
    "SteelSeries Arctis 1":           "https://m.media-amazon.com/images/I/71oguR2E8yL._AC_SX679_.jpg",
    "SteelSeries Arctis 7":           "https://m.media-amazon.com/images/I/71oguR2E8yL._AC_SX679_.jpg",
    "SteelSeries Arctis Nova 3":      "https://m.media-amazon.com/images/I/71oguR2E8yL._AC_SX679_.jpg",
    "SteelSeries Arctis Nova 7 Wireless":"https://m.media-amazon.com/images/I/71oguR2E8yL._AC_SX679_.jpg",
    "SteelSeries Arctis Nova Pro":    "https://m.media-amazon.com/images/I/71oguR2E8yL._AC_SX679_.jpg",
    "SteelSeries Arctis Nova Pro Wireless":"https://m.media-amazon.com/images/I/71oguR2E8yL._AC_SX679_.jpg",
    "Logitech G Pro X 2 Lightspeed":  "https://m.media-amazon.com/images/I/71KJCyVxI+L._AC_SX679_.jpg",
    "Logitech G231 Prodigy":          "https://m.media-amazon.com/images/I/71KJCyVxI+L._AC_SX679_.jpg",
    "Logitech G432 7.1":              "https://m.media-amazon.com/images/I/71KJCyVxI+L._AC_SX679_.jpg",
    "Logitech G733 Wireless":         "https://m.media-amazon.com/images/I/71KJCyVxI+L._AC_SX679_.jpg",
    "Corsair HS35 Stereo":            "https://m.media-amazon.com/images/I/61lUNdU9qXL._AC_SX679_.jpg",
    "Corsair HS65 Surround":          "https://m.media-amazon.com/images/I/61lUNdU9qXL._AC_SX679_.jpg",
    "Corsair HS80 RGB Wireless":      "https://m.media-amazon.com/images/I/61lUNdU9qXL._AC_SX679_.jpg",
    "Corsair Virtuoso Pro":           "https://m.media-amazon.com/images/I/61lUNdU9qXL._AC_SX679_.jpg",
    "Corsair Virtuoso RGB Wireless XT":"https://m.media-amazon.com/images/I/61lUNdU9qXL._AC_SX679_.jpg",
    "Razer BlackShark V2":            "https://m.media-amazon.com/images/I/71AKpCzQRQL._AC_SX679_.jpg",
    "Razer Kraken V3 Pro Wireless":   "https://m.media-amazon.com/images/I/71AKpCzQRQL._AC_SX679_.jpg",
    "Razer Kraken X":                 "https://m.media-amazon.com/images/I/71AKpCzQRQL._AC_SX679_.jpg",
    "Razer Nari Ultimate Wireless":   "https://m.media-amazon.com/images/I/71AKpCzQRQL._AC_SX679_.jpg",
    "Razer Barracuda Pro Wireless":   "https://m.media-amazon.com/images/I/71AKpCzQRQL._AC_SX679_.jpg",
    "Audeze Maxwell Wireless":        "https://m.media-amazon.com/images/I/71AKpCzQRQL._AC_SX679_.jpg",
    # ── MONITOARE ───────────────────────────────────────────────────────────
    "ASUS ROG Swift OLED PG27AQDM 27\" 240Hz":"https://m.media-amazon.com/images/I/81RJVZ1DKZL._AC_SX679_.jpg",
    "ASUS ROG Swift PG279QM 27\"":     "https://m.media-amazon.com/images/I/81RJVZ1DKZL._AC_SX679_.jpg",
    "ASUS ROG Swift PG279QM 27\" 240Hz":"https://m.media-amazon.com/images/I/81RJVZ1DKZL._AC_SX679_.jpg",
    "ASUS ROG Swift PG32UQX 32\" 4K 144Hz":"https://m.media-amazon.com/images/I/81RJVZ1DKZL._AC_SX679_.jpg",
    "ASUS ROG Strix XG27AQM 27\" 270Hz QHD":"https://m.media-amazon.com/images/I/81RJVZ1DKZL._AC_SX679_.jpg",
    "ASUS ProArt PA279CV 27\" 4K":     "https://m.media-amazon.com/images/I/71mD7DumLWL._AC_SX679_.jpg",
    "ASUS TUF Gaming VG249Q 24\" 165Hz":"https://m.media-amazon.com/images/I/71mD7DumLWL._AC_SX679_.jpg",
    "AOC 24G2 24\" 144Hz":             "https://m.media-amazon.com/images/I/71V0jVa7FRL._AC_SX679_.jpg",
    "AOC Q27G2S 27\" 165Hz QHD":       "https://m.media-amazon.com/images/I/71V0jVa7FRL._AC_SX679_.jpg",
    "LG 24GN650 24\" 144Hz":           "https://m.media-amazon.com/images/I/71rkWdQ+VoL._AC_SX679_.jpg",
    "LG 27GP850-B 27\" 165Hz":         "https://m.media-amazon.com/images/I/71rkWdQ+VoL._AC_SX679_.jpg",
    "LG 27GP850-B 27\" 165Hz QHD":     "https://m.media-amazon.com/images/I/71rkWdQ+VoL._AC_SX679_.jpg",
    "LG 27UK850 27\" 4K 60Hz":         "https://m.media-amazon.com/images/I/71rkWdQ+VoL._AC_SX679_.jpg",
    "LG 32GQ950 32\" 160Hz 4K":        "https://m.media-amazon.com/images/I/71rkWdQ+VoL._AC_SX679_.jpg",
    "LG 45GR95QE 45\" OLED 240Hz":     "https://m.media-amazon.com/images/I/71rkWdQ+VoL._AC_SX679_.jpg",
    "Samsung Odyssey G3 27\" 144Hz":   "https://m.media-amazon.com/images/I/71ABe1GVGWL._AC_SX679_.jpg",
    "Samsung Odyssey G7 32\"":         "https://m.media-amazon.com/images/I/71ABe1GVGWL._AC_SX679_.jpg",
    "Samsung Odyssey G7 32\" 240Hz":   "https://m.media-amazon.com/images/I/71ABe1GVGWL._AC_SX679_.jpg",
    "Samsung Odyssey G9 49\" 240Hz":   "https://m.media-amazon.com/images/I/71ABe1GVGWL._AC_SX679_.jpg",
    "Samsung Odyssey OLED G8 34\" 175Hz":"https://m.media-amazon.com/images/I/71ABe1GVGWL._AC_SX679_.jpg",
    "BenQ MOBIUZ EX2710Q 27\"":        "https://m.media-amazon.com/images/I/71V0jVa7FRL._AC_SX679_.jpg",
    "BenQ MOBIUZ EX2710Q 27\" QHD":    "https://m.media-amazon.com/images/I/71V0jVa7FRL._AC_SX679_.jpg",
    "MSI G274QPF-QD 27\" 170Hz QHD":   "https://m.media-amazon.com/images/I/71V0jVa7FRL._AC_SX679_.jpg",
    "ViewSonic XG2405 24\" 144Hz":     "https://m.media-amazon.com/images/I/71V0jVa7FRL._AC_SX679_.jpg",
}

# ── Ruleaza importul ─────────────────────────────────────────────────────────
products = db.query(Product).all()
added = 0
skipped = 0

for product in products:
    # Skip products that already have an image (to preserve manually added ones)
    existing = db.query(ProductImage).filter(ProductImage.product_id == product.id).first()
    if existing:
        skipped += 1
        continue

    url = PRODUCT_IMAGES.get(product.name)
    if url:
        img = ProductImage(
            product_id=product.id,
            url=url,
            sort_order=0,
        )
        db.add(img)
        added += 1
    else:
        print(f"  [FARA IMAGINE] {product.name}")

db.commit()
db.close()
print(f"\nRezultat: {added} imagini adaugate, {skipped} produse aveau deja imagini")
